### ISSUE TITLE
Add Guzzle option in .ini to disable certificate verification

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#258] opened 2016-10-25 22:03 UTC
If Guzzle can't find the path to a certificate bundle, it throws up errors and won't download files. Add option to disable certificate verification to fix this easily.

**Comment by mjordan** [comment] 2016-10-26 00:46
We can probably disable CA verification as documented at http://docs.guzzlephp.org/en/latest/request-options.html?highlight=client%20verify#verify by providing an .ini option like the `[FILE_GETTER] http_timeout` configuration option. In the OAI-PMH toolchain, we create the Guzzle client in the Writer (https://github.com/MarcusBarnes/mik/blob/master/src/writers/Oaipmh.php#L65), which is where we'd want to set the client's verify option to `false` if indicated in the .ini file.

Unfortunately, I don't have easy acess to a Mac, where this is known issue. @MarcusBarnes, perhaps you could investigate as time allows?

**Comment by MarcusBarnes** [comment] 2016-10-26 16:42
I'm hesitant to add this as a configuration option, since this technically makes things less secure and people may copy configuration files to projects where CA verification is vital.   My hope is that the issue with Mac's and Guzzle can be resolved by the respective communities (outside of MIK).   However, it would definitely make it easier for me (as a regular Mac user) to simply include a line in the configuration file, rather than manually modifying the each use of Guzzle's client verify option to false in a given toolchain.  @bondjimbond Which toolchain are you currently using where this is coming up?

**Comment by MarcusBarnes** [comment] 2016-10-26 16:42
@bondjimbond Would you also share which OS X version you're using?

**Comment by bondjimbond** [comment] 2016-10-26 16:54
El Capitan (10.11.5). 

I'm using the OAI toolchain. I think that's the only one that uses Guzzle.

**Comment by bondjimbond** [comment] 2016-10-26 16:57
I wouldn't want to wait for the Guzzle people to solve the issue, since we want MIK to work _now_... Definitely would be happy to see the option to skip verification in the .ini file.

**Comment by MarcusBarnes** [comment] 2016-10-26 17:05
@bondjimbond @mjordan I'll see what I can do - starting with the OAI toolchain.   @bondjimbond I may ask that you help test.   Thanks.

**Comment by mjordan** [comment] 2016-10-26 18:11
The CONTENTdm toolchains also use Guzzle, but the reason this didn't come up during our migration was that our CONTENTdm wasn't running https.

@MarcusBarnes I appreciate your point about security, but most of the time running MIK against a remote repository will be short-lived during migrations. I don't see a problem with this as long as we document any workarounds we build into MIK so that users are aware of the risks and accept them.

**Comment by MarcusBarnes** [comment] 2016-10-26 18:31
@mjordan Thanks.  We'd also remove such functionality once this is no longer an issue with Macs.

**Comment by mjordan** [comment] 2016-10-26 18:57
Agreed - removing it when it's no longer necessary will mean simpler configuration and simpler code :smile:

**Comment by mjordan** [comment] 2016-10-26 19:13
I just ran issue-255 on our Windows VM here with not complaints about certificates, so this might be an OSX issue only (although we probably should test on more Windows and Linux machines to make sure).

**Comment by MarcusBarnes** [comment] 2016-10-26 19:16
Should the issue-255 branch be merged before I do work on this issue?

**Comment by mjordan** [comment] 2016-10-26 19:18
Probably, since the new and improved OAI toolchain is where this issue is easiest to test.

**Comment by MarcusBarnes** [comment] 2016-10-26 19:24
OK.  I'll wait until the issue-255 branch is merged, then I will work on this issue.

**Comment by mjordan** [comment] 2016-10-26 19:45
@MarcusBarnes unless you want to do further testing on issue-255, I think it's ready to merge. I can open a PR if you want.

**Comment by MarcusBarnes** [comment] 2016-10-26 19:50
@mjordan Please create a pull-request.   Thanks.

**Comment by mjordan** [comment] 2016-10-26 19:55
Done!

**Comment by MarcusBarnes** [comment] 2016-10-28 13:06
For reference, this comment gives an explanation of why this happens on Macs and how to adjust things on your Mac so that CA verification issue no longer comes up:  http://stackoverflow.com/questions/26461966/osx-10-10-curl-post-to-https-url-gives-sslread-error/26538127#26538127

However, since it may not always be possible for an MIK user to implement the adjustments on their system, I have an initial workaround pending for the basic OAI toolchain as requested in this issue.

**Comment by MarcusBarnes** [comment] 2016-10-28 13:57
@bondjimbond @mjordan I've addressed this for the basic OAI toolchain.   Please review and test the pull-request https://github.com/MarcusBarnes/mik/pull/261.  If @mjordan feels comfortable merging, we can apply similar logic to other toolchains.   Thank you.

**Comment by bondjimbond** [comment] 2016-10-28 19:59
It works! I got my downloads, and only four items in the problem records log:

[2016-10-28 18:53:19] ProblemRecords.INFO: Initializing log {"configuration":{"config_id":"KORA migration","last_updated_on":"2016-10-22","last_update_by":"mj"}} []
[2016-10-28 19:04:12] ProblemRecords.ERROR: oai%3Akora.kpu.ca%3Afacultypub-1077 [] []
[2016-10-28 19:04:13] ProblemRecords.ERROR: oai%3Akora.kpu.ca%3Afacultypub-1157 [] []
[2016-10-28 19:04:14] ProblemRecords.ERROR: oai%3Akora.kpu.ca%3Afacultypub-1125 [] []
[2016-10-28 19:04:15] ProblemRecords.ERROR: oai%3Akora.kpu.ca%3Afacultypub-1137 [] []

**Comment by mjordan** [comment] 2016-10-28 20:39
Awesome! The four problem items are the same ones I have been getting. The source repository is returning a 404 in response to the request for the PDF. 
I'll merge this weekend. Thanks Marcus!
On 28 Oct 2016 12:59 p.m., Brandon Weigel <notifications@github.com> wrote:It works! I got my downloads, and only four items in the problem records log:

[2016-10-28 18:53:19] ProblemRecords.INFO: Initializing log {"configuration":{"config_id":"KORA migration","last_updated_on":"2016-10-22","last_update_by":"mj"}} []
[2016-10-28 19:04:12] ProblemRecords.ERROR: oai%3Akora.kpu.ca%3Afacultypub-1077 [] []
[2016-10-28 19:04:13] ProblemRecords.ERROR: oai%3Akora.kpu.ca%3Afacultypub-1157 [] []
[2016-10-28 19:04:14] ProblemRecords.ERROR: oai%3Akora.kpu.ca%3Afacultypub-1125 [] []
[2016-10-28 19:04:15] ProblemRecords.ERROR: oai%3Akora.kpu.ca%3Afacultypub-1137 [] []

**Comment by mjordan** [comment] 2016-10-29 14:42
Tested (on Llinux, not OS X) with `[SYSTEM] verify_ca = false` absent, and with it present. Every appeared to work as intended.

I'll add this nice new feature to the other toolchains that use Guzzle, test as above, and merge.

Nice work @MarcusBarnes and @bondjimbond.

**Comment by mjordan** [comment] 2016-10-29 16:38
In addition Marcus' addition of this feature to 'src/writers/Oaipmh.php',  04f37f0 adds it to the following classes that use Guzzle clients:

* src/config/Config.php
* src/fetchermanipulators/CdmByDmDate.php
* src/filegetters/CdmCompound.php
* src/filegetters/CdmNewspapers.php
* src/filegetters/CdmPhpDocuments.php
* src/filegetters/CdmSingleFile.php
* src/filegetters/OaipmhOjsPdf.php
* src/filegetters/OaipmhXpath.php
* src/metadatamanipulators/AddContentdmData.php

I've only tested one CONTENTdm toolchain, CdmSingleFile, but everything works as intended. I'll be doing a few more CONTENTdm migrations in the next couple of weeks so will keep an eye out then for any issues. I'll merge the PR in a few miniutes and close this issue.

**Comment by mjordan** [comment] 2016-10-29 17:08
OK, I've updated all the toolchain wiki pages to document this feature, and I've merged the PR.

**Closed by mjordan** 2016-10-29 17:08 UTC
