### ISSUE TITLE
OAI toolchain: files-only config setting?

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#301] opened 2016-11-25 23:20 UTC
Would it be possible to add a configuration to just extract files, rather than getting XML as well? Use case would be the two-stage Digital Commons migration: step 1 - download all files via OAI, step 2 - generate metadata via CSV.

**Comment by mjordan** [comment] 2016-11-25 23:27
Yes. #257 would address this. What's your timeline?

Can I mark this a duplicate of #257?

**Comment by bondjimbond** [comment] 2016-11-25 23:39
In #257, would OBJ mean "just write the file referenced in xpath_expression", and OAI "just write the XML"?

If so, then yes, it's a duplicate.

**Comment by mjordan** [comment] 2016-11-25 23:42
I think so, but what xpath_expression are you referring to?

**Comment by bondjimbond** [comment] 2016-11-25 23:43
i.e. `<dc:identifier>[2]` - the xpath to the downloadable file.

**Comment by bondjimbond** [comment] 2016-11-25 23:45
Re timeline: no timeline, just something I thought of i process of writing up the Digital Commons migration guide. If you're starting out with a plan to use OAI to download files and CSV to get metadata, there's no need to download the Dublin Core XML or transform it to MODS.

**Comment by mjordan** [comment] 2016-11-25 23:53
Yes, OBJ is what we've been using for the file that will correspond to the OBJ datastream, which for the OAI toolchain for Digital Commons that would be correct. #257 will address this.

**Comment by mjordan** [comment] 2016-11-25 23:54
Duplicate of #257.

**Closed by mjordan** 2016-11-25 23:54 UTC

**Comment by mjordan** [comment] 2017-03-31 02:54
@bondjimbond looking at this now, I think it's not possible to not do an OAI harvest, since it's only through an OAI harvest that we'd know which files to then get. Does that make sense? If you didn't want to see the .xml files in your output directory because you have metadata from a CSV (your use case), you could just delete the *.xml files.
