### ISSUE TITLE
Let git manage source code line endings across platforms

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#310] opened 2016-12-09 00:09 UTC
It's common  practice to add a .gitattributes file to a repo and in it, indicate that all text files should be normalized to LF on commit and back to the native line ending (CRLF on Windows) on checkout/clone. A sample .gitattributes file that would apply to MIK is:

```
mik text
*.php text
*.csv text
*.ini text

*.tiff binary
```

I'm happy to test this since I'm working with MIK both on Linux and Windows.

**Comment by MarcusBarnes** [comment] 2016-12-09 15:34
@mjordan Excellent suggestion.  If you could please test on Linux and Windows, that would be great, since I can test on a Mac.

**Comment by mjordan** [comment] 2016-12-12 00:11
@MarcusBarnes tested this by adding .gitattributes similar to above on Linux, then pushing to my fork. Then cloned my fork to Windows and opened a file. Line endings were converted to CLRF. Made a change in Windows and committed it back to my fork. Cloned to a new repo in Linux and opened modified file, and line endings were LF. So this appears to work as intended. If you open a file from this branch on OSX, your line endings should be LF.

**Comment by MarcusBarnes** [comment] 2016-12-12 14:46
This confirmed that when I opened a file from this branch on OSX and my line endings were LF as expected.  Please feel free to create a pull-request.

**Comment by mjordan** [comment] 2016-12-12 14:56
Sweet, thanks, will do.

**Comment by MarcusBarnes** [comment] 2016-12-13 15:16
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/313 (merged with commit https://github.com/MarcusBarnes/mik/commit/773a629e8d250e08c7ae7be313c271af2fcfef8e).

**Closed by MarcusBarnes** 2016-12-13 15:16 UTC
Labels: house cleaning

**Comment by mjordan** [comment] 2016-12-13 15:30
Thanks @MarcusBarnes!
