### ISSUE TITLE
CSVBooks: MIK fails when output directory doesn't exist

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#457] opened 2018-03-05 20:05 UTC
In CSV Single File, if you set an output_directory that doesn't exist yet, MIK creates it for you without problems.

In CSV Books, however, MIK fails. Logs the following error:

> ErrorException.ERROR: ErrorException {"message":"mkdir(): No such file or directory"

If you create the output_directory and leave the config file alone, it runs just fine.

**Comment by mjordan** [comment] 2018-03-05 20:22
I'll take care of this.

**Comment by mjordan** [comment] 2018-03-18 15:47
@bondjimbond I just opened #459 and, strangely, did not see this behaviour while running my new code numerous times. If you have time to test that PR, can you confirm that the problem still exists?

**Comment by bondjimbond** [comment] 2018-03-20 20:32
@MarcusBarnes Re the question of permissions: It shouldn't be a permissions thing, since it's only the CSV Books toolchain that fails to create the directory. Other toolchains (CSV Single File) do it without problems.

**Comment by bondjimbond** [comment] 2018-03-29 15:21
Update: Error also occurs in CsvCompound toolchain.

**Comment by MarcusBarnes** [comment] 2018-04-15 16:26
@mjordan I'll schedule some time to attempt to reproduce the issue early this week and report back on this issue thread.

**Comment by bondjimbond** [comment] 2018-09-17 14:29
@MarcusBarnes Any update on reproducing the problem?

**Comment by MarcusBarnes** [comment] 2018-09-17 18:47
Confirming that for CSVBook,  if you set an output_directory that doesn't exist yet, you get an error:

>[2018-09-17 17:57:25] ErrorException.ERROR: ErrorException {"message":"mkdir(): No such file or directory","code" .. "file":"../src/writers/CsvBooks.php","line":96} []'

**Comment by MarcusBarnes** [comment] 2018-09-17 18:55
Looking at CSVSingleFile, it uses the [createOutputDirectory()](https://github.com/MarcusBarnes/mik/blob/master/src/writers/Writer.php#L130) method:  

https://github.com/MarcusBarnes/mik/blob/master/src/writers/CsvSingleFile.php#L64

Following a similar pattern from CSVSingleFile in CSVBook from about [L84 to L97](https://github.com/MarcusBarnes/mik/blob/master/src/writers/CsvBooks.php#L84-L97) should resolve this issue.

**Comment by mjordan** [comment] 2018-09-17 19:44
I'm not saying my previous testing was iron-clad, but it's strange the I couldn't replicate this problem on Linux, and I use the compound toolchain frequently (not sow much the book toolchain) at work on Windows. @MarcusBarnes just to be sure, could you run the same config, etc. you used to confirm this on your Mac on a linux VM like the Islandora Vagrant? I'll also replicate my attempts to reproduce this on Linux.

I can't explain why in my attempts an output directory gets created despite the absence of the `createOutputDirectory()` method, which is even more reason for me to retry my attempts.

**Comment by MarcusBarnes** [comment] 2018-09-17 19:54
@mjordan Despite my pull-request, I now know what the issue is now based on your most recent comment.  In the `createOutputDirectory` method, we are explicitly providing the MODE parameter for `mkdir`, whereas in the CSVBook writer, we are not.

Compare 

https://github.com/MarcusBarnes/mik/blob/master/src/writers/Writer.php#L135

with 

https://github.com/MarcusBarnes/mik/blob/master/src/writers/CsvBooks.php#L96

We can modify my pull-request or just leave it as is, since it's usuful for future contributions to CSVBook to know about the `createOutputDirectory` method from the parent Writer class.

See http://php.net/manual/en/function.mkdir.php for the PHP Documentation on the `mkdir` function.

**Comment by mjordan** [comment] 2018-09-17 19:57
@MarcusBarnes good catch. Modifying your current PR is probably the most complete fix if you're OK with that.

**Comment by mjordan** [comment] 2018-09-17 19:58
Just curious, does what you've discovered explain any differences between OSX and Linux?

**Comment by MarcusBarnes** [comment] 2018-09-17 20:00
@mjordan I'm OK with modifying my pull-request.  Do you want me to leave the call to createOutputDirectory?

**Comment by mjordan** [comment] 2018-09-17 20:01
Yes, I think for consistency, we should be using that method everywhere, since it is defined in the parent class.

**Comment by MarcusBarnes** [comment] 2018-10-31 17:59
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/489 (merged with commit https://github.com/MarcusBarnes/mik/commit/38514834edb30b4a2513e0638605ea23560bb3e2).

**Closed by MarcusBarnes** 2018-10-31 17:59 UTC
Labels: bug
